x=complex(input("enter the first complex number "))
y=complex(input("enter  the second complex  number"))
print(type(x)," ",type(y))
print("addition",x+y)
print("sub",x-y)
print("floral div",x/y)
print("mul",x*y)
print("power",x**y)